function chantable
f = gcf;
global CHANCHOICES
t = uitable('Parent',f,...
    'units', 'normalized', ...
    'Position', [.05 .10 .9 .80], ...  
    'data',CHANCHOICES,...
    'ColumnEditable', true, ...
    'CellEditCallback', 'global CHANCHOICES; CHANCHOICES = get(gco, ''Data'');');
end
