function [okayhit, IC_choices]=ICpick(fnames,numconds)

%size of largest number of subjects gives size of grid
tabsize=max(cell2mat(cellfun(@length,fnames,'un',0)));

evstring='global ICCHOICES; ICCHOICES=repmat(cellstr(''''),tabsize,numconds*numconds); ICtable;';


[res, jnk, okayhit]=inputgui( ...
    'geom', ...
    {...
    {6 22 [0 0] [1 1]} ... % this is just to control the size of the GUI {6 22 [0 0] [1 1]} ...
    {6 22 [0.05 0] [2 1]} ... % load config
    {6 22 [3.95 0] [2 1]} ... %2 saveas
    
    }, ...
    'uilist', ...
    {...
    {'Style', 'text', 'tag','txt_ccfp','string',blanks(30)} ... %1 this is just to control the size of the GU
    {'Style', 'pushbutton', 'string', 'Load Parameters', ...
    'callback', ...
    ['[ParamName, ParamPath] = uigetfile(''*.mat'',''Select IC cluster file:'',''*.mat'',''multiselect'',''off'');', ...
    'load(fullfile(ParamPath, ParamName),''-mat'');']} ... %2
    {'Style', 'pushbutton','string','Save IC cluster file', ...
    'callback',['[ParamName, ParamPath]=uiputfile(''*.*'',''IC cluster file'');', ...
    'global STATSLAB_PROPERTIES; statslab_propgrid=propgrid2struct(STATSLAB_PROPERTIES);', ...
    'save(fullfile(ParamPath, ParamName),''curdata'');']}, ...
    }, ...
    'title', 'STATSLAB -- statslab()',...%, ...
    'eval',evstring ...
    );
global ICCHOICES
IC_choices=cellfun(@str2num,ICCHOICES(1:end),'UniformOutput',0)';
clearvars -global ICCHOICES
end


% trialdat=squeeze(double(EEG.data(18,:,:)))';
% subplot(2,1,1)
% x=EEG.times;
% y=1:EEG.trials;
% surf(x,y,trialdat,'linestyle','none','facecolor','interp'); axis tight; view(0,90);
% subplot(2,1,2)
% plot(x,mean(trialdat)); axis tight; grid on;

