function [properties]=propgridbuild(statslab_propgrid)


switch nargin
    case 0
        empt='';
        emptcell={''};
        
        properties = [ ...
            PropertyGridField('condnames', emptcell, ... % extract
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Extract Data', ...
            'DisplayName', 'condnames', ...
            'Description', propdoc('ExtractData','***condnames***','***end***')) ...
            PropertyGridField('condfiles_extract', empt, ...
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Extract Data', ...
            'DisplayName', 'condfiles', ...
            'Description', propdoc('ExtractData','***condfiles***','***end***')) ...
            PropertyGridField('levels', 2, ...
            'Category', 'Extract Data', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'levels', ...
            'Description', 'levels in your design (e.g., for a 3X2 input 3 2. For a t-test (paired or unpaired) input 2).') ...
            PropertyGridField('design', 'w', ...
            'Type', PropertyType('char', 'row', {'w','ww','b','bb', 'bw'}), ...
            'Category', 'Extract Data', ...
            'DisplayName', 'design', ...
            'Description', sprintf(['A keystring indicating your type of design, for example:\n', ...
            '1-way within subjects = w\n2-way within-subjects = ww\n', ...
            '1-way between-subjects = b\n2-way between-subjects = bb\nMixed designs = bw'])) ...
            PropertyGridField('savestring', empt, ...
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Extract Data', ...
            'DisplayName', 'savestring', ...
            'Description', sprintf(['A string that identifies your analysis ', ...
            '(e.g. occipital_GFA_analysis). The main STATS structure, which accumulates parameters, will have this string appended to it.\n', ...
            'Leave empty and a browser will appear asking for you to load a previously saved STATS structure.'])) ...
            PropertyGridField('varargin_extract', emptcell, ...
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Extract Data', ...
            'DisplayName', 'varargin', ...
            'Description', propdoc('ExtractData','***varargin***','***end***')) ...
            PropertyGridField('logical_extract', false, ...
            'Category', 'Extract Data', ...
            'DisplayName', 'Run ExtractData.m', ...
            'Description', 'Check box to run current STATSLAB module once OK is pressed.') ...
            PropertyGridField('condfiles_resample', empt, ... % resample
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Resample Data', ...
            'DisplayName', 'condfiles', ...
            'Description', ['A .mat file which holds the filenames for each file you would like to resample. ',...
            'Leave empty and a browser will appear so that you can choose the files ']) ...
            PropertyGridField('nboot', 1000, ...
            'Category', 'Resample Data', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'nboot', ...
            'Description', 'number of bootstrap resamples from the single trials (default=1000)') ...
            PropertyGridField('varargin_resample', emptcell, ...
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Resample Data', ...
            'DisplayName', 'varargin', ...
            'Description', sprintf(['Optional trial cap can be specified which caps the number of trials used in the resampling procedure\n', ...
            'Leave empty or set ''trialcap'', ''none'' for no trial cap\n', ...
            'Set ''trialcap'', 75 to limit resampling to 75 trials.'])) ...
            PropertyGridField('logical_resample', false, ...
            'Category', 'Resample Data', ...
            'DisplayName', 'Run ResampleData.m', ...
            'Description', 'Check box to run current STATSLAB module once OK is pressed. Will run after completion of subsequent module.') ...
            PropertyGridField('condfiles_group', empt, ... % group stat
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Group Statistics', ...
            'DisplayName', 'condfiles', ...
            'Description', ['A .mat file which holds the filenames with "bootstrapped" appended to them (i.e., the output files of the resampling procedure), in the form of subject X condition cell arrays. ', ...
            'Leave empty and a browser will appear so that you can choose the bootstrapped files ']) ...
            PropertyGridField('alpha_group', 0.05, ...
            'Category', 'Group Statistics', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'alpha', ...
            'Description', 'arbitrary significance cutoff. Will be adjusted if control for FWE is selected') ...
            PropertyGridField('nsamp', 1000, ...
            'Category', 'Group Statistics', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'nsamp', ...
            'Description', 'Number of resamples taken at the group level (resampling of subjects). This can take a long time (default = 1000)') ...
            PropertyGridField('varargin_group', emptcell, ...
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Group Statistics', ...
            'DisplayName', 'varargin', ...
            'Description', sprintf(['Optional control for FWE and specification of linear contrasts.\n', ...
            'For example, consider testing all pairwise comparisons and the interaction in a 2x2 design with Rom''s method of FWE control:\n', ...
            '''FWE'', ''Rom'', ''conA'', [1 0 -1 0; 0 1 0 -1]'', ''conB'', [1 -1 0 0; 0 0 1 -1]'', ''conAB'', [1 -1 -1 1]''\n', ...
            'Do not forget the transpose operator at the end of the contrasts matrices (i.e., '' ).\n', ...
            'See documentation and function header (help GroupStatistics) for many more examples. '])) ...
            PropertyGridField('logical_group', false, ...
            'Category', 'Group Statistics', ...
            'DisplayName', 'Run GroupStatistics.m', ...
            'Description', 'Check box to run current STATSLAB module once OK is pressed. Will run after completion of subsequent module.') ...
            PropertyGridField('condfiles_subject', empt, ... % sub stat
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Subject Statistics', ...
            'DisplayName', 'condfiles', ...
            'Description', ['A .mat file which holds the filenames with "bootstrapped" appended to them (i.e., the output files of the resampling procedure), in the form of subject X condition cell arrays. ', ...
            'Leave empty and a browser will appear so that you can choose the bootstrapped files ']) ...
            PropertyGridField('alpha_subject', 0.05, ...
            'Category', 'Subject Statistics', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'alpha', ...
            'Description', 'arbitrary significance cutoff. Will be adjusted if control for FWE is selected') ...
            PropertyGridField('varargin_subject', emptcell, ...
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Subject Statistics', ...
            'DisplayName', 'varargin', ...
            'Description', sprintf(['Optional control for FWE and specification of linear contrasts.\n', ...
            'Contrast matrices are constructed in the same way as in the Group Statistics module.\n' , ...
            'However, see documentation for the exception when dealing with single-subject statistics in between-within (mixed) designs.\n'])) ...
            PropertyGridField('logical_subject', false, ...
            'Category', 'Subject Statistics', ...
            'DisplayName', 'Run SubjectStatistics.m', ...
            'Description', 'Check box to run current STATSLAB module once OK is pressed. Will run after completion of subsequent module.') ...
            PropertyGridField('infodisplay_group', true, ... % group fig
            'Category', 'Group Figure', ...
            'DisplayName', 'infodisplay', ...
            'Description', 'Numerical flag. If set STATSLAB will display condition labels and contrast matrices for reference.') ...
            PropertyGridField('varargin_groupfig', emptcell, ...
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Group Figure', ...
            'DisplayName', 'varargin', ...
            'Description', sprintf(['Optional inputs for displaying group figures.\n', ...
            '''all'' will show figures for all previously specified contrasts. If you would like to plot only a subset of the comparisons,\n', ...
            'specify the appropriate key/val pairs. For example, to plot the 1st and 2nd factor B comparisons, as well as the 1st interaction,\n', ...
            'use ''FactorB'', [1 2], ''FactorAB'', 1\n', ...
            'See documentation and function header (help GroupFigure) for many more examples. '])) ...
            PropertyGridField('logical_groupfig', false, ...
            'Category', 'Group Figure', ...
            'DisplayName', 'Run GroupFigure.m', ...
            'Description', 'Check box to run current STATSLAB module once OK is pressed. Will run after completion of subsequent module.') ...
            PropertyGridField('infodisplay_sub', true, ... % sub fig
            'Category', 'Subject Figure', ...
            'DisplayName', 'infodisplay', ...
            'Description', 'Numerical flag. If set STATSLAB will display condition labels and contrast matrices for reference.') ...
            PropertyGridField('varargin_subjectfig', emptcell, ...
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Subject Figure', ...
            'DisplayName', 'varargin', ...
            'Description', sprintf(['Optional inputs for displaying subject figures. There are various visualizations available.\n', ...
            'To plot subject difference waves with specific colors and Y axis range:\n', ...
            '''plottype'', ''wave'', ''diffcol'', [.8 0 0], ''CIcol'', [0 .9 0], ''yaxis'', [-4 4]\n', ...
            'To plot subject difference waves as colorbars with a color range (caxis):\n', ...
            '''plottype'', ''diff'', ''caxis'', [-4 4]\n', ...
            'To plot subject difference waves as colorbars with margin of error information on the Y axis (i.e., mean varies by +/- some amount):\n', ...
            '''plottype'', ''MOE'', ''caxis'', [-4 4], ''zaxis'', [0 3]\n'])) ...
            PropertyGridField('logical_subjectfig', false, ...
            'Category', 'Subject Figure', ...
            'DisplayName', 'Run SubjectFigure.m', ...
            'Description', 'Check box to run current STATSLAB module once OK is pressed. Will run after completion of subsequent module.') ...
            PropertyGridField('infodisplay_cor', true, ... % winbootcor
            'Category', 'Robust Correlations', ...
            'DisplayName', 'infodisplay', ...
            'Description', 'Numerical flag. If set STATSLAB will display your contrasts, condition names, Xlables, and Ylables.') ...
            PropertyGridField('nboot_cor', 1000, ...
            'Category', 'Robust Correlations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'nboot', ...
            'Description', 'number of bootstrap resamples from the x and y data. Default=1000') ...
            PropertyGridField('tr', .2, ...
            'Category', 'Robust Correlations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'trim', ...
            'Description', 'percentage to winsorize from the X and Y data. Keep as decimal place (e.g., .2 for 20%, .5 for 50% etc). Wilcox (2012) recommends .2 in many cases') ...
            PropertyGridField('Ylabel_cor', emptcell, ...
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Robust Correlations', ...
            'DisplayName', 'Ylabel', ...
            'Description', sprintf(['A string, or cell array of strings, indicating your Y variable(s) that will each be correlated, one by one, with your EEG waveforms (X variable). For example,\n ', ...
            'RTs accuracy perfectionism_scores'])) ...
            PropertyGridField('varargin_cor', emptcell, ...
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Robust Correlations', ...
            'DisplayName', 'varargin', ...
            'Description', sprintf(['String and numerical pair indicating the EEG data you would like to use in the correlation. For example, ''Condition'', 3\n' ...
            'would correlate data from condition 3 with each Y variable. To use difference waves as the X variable there are three varargin inputs. For example, ''FactorB'', 2, ''my_comparison''\n', ...
            'would use the 2nd FactorB waveform as the X variable in the correlation and name this comparison, ''my_comparison''\n', ...
            'See documentation for subtle differences when using mixed designs'])) ...
            PropertyGridField('logical_cor', false, ...
            'Category', 'Robust Correlations', ...
            'DisplayName', 'Run WinBootCor.m', ...
            'Description', 'Check box to run current STATSLAB module once OK is pressed.') ...
            PropertyGridField('condition_label_rw', empt, ... % Linear & nonlinear visualizations wincorboot figure
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'condition/contrast label (X variable)', ...
            'Description', 'Label of one of your conditions or contrasts that was used previously when calculating correlations.') ...
            PropertyGridField('Ylabel_rw', empt, ...
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'Ylabel (Y variable)', ...
            'Description', 'Ylabel used in a previous correlation.') ...
            PropertyGridField('logical_rw', false, ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'Run WinBootCorFigure.m', ... % does not exist yet
            'Description', 'Check box to run WinBootCorFigure.m once OK is pressed.') ...
            PropertyGridField('infodisplay_slope', true, ... % slope
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'infodisplay', ...
            'Description', 'Numerical flag. If set STATSLAB will display your contrasts, condition names, Xlables, and Ylables.') ...
            PropertyGridField('condition_label_slope', empt, ...
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'condition/contrast label (X variable)', ...
            'Description', 'Label of one of your conditions or contrasts that was used previously when calculating correlations.') ...
            PropertyGridField('Ylabel_slope', empt, ...
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'Ylabel (Y variable)', ...
            'Description', 'Ylabel used in a previous correlation.') ...
            PropertyGridField('msplot_slope', [], ...
            'Category', 'Linear & nonlinear visualizations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'msplot', ...
            'Description', 'A number indicating the millisecond latency at which to make the scatterplot ') ...
            PropertyGridField('CI_color_slope', [.5 .5 .5], ...
            'Category', 'Linear & nonlinear visualizations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'CI_color', ...
            'Description', 'The color of the CI and prediction band. This is in the form of an RGB triplet') ...
            PropertyGridField('CI_limit_slope', [1 1 1], ...
            'Category', 'Linear & nonlinear visualizations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'CI_limit', ...
            'Description', ' The color that the CI will fade to as it increases in width.') ...
            PropertyGridField('logical_slope', false, ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'Run SlopeCI.m', ...
            'Description', 'Check box to run SlopeCI.m once OK is pressed.') ...
            PropertyGridField('infodisplay_lowess', true, ... % LOWESS
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'infodisplay', ...
            'Description', 'Numerical flag. If set STATSLAB will display your contrasts, condition names, Xlables, and Ylables.') ...
            PropertyGridField('condition_label_lowess', empt, ...
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'condition/contrast label (X variable)', ...
            'Description', 'Label of one of your conditions or contrasts that was used previously when calculating correlations.') ...
            PropertyGridField('Ylabel_lowess', empt, ...
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'Ylabel (Y variable)', ...
            'Description', 'Ylabel used in a previous correlation.') ...
            PropertyGridField('msplot_lowess', [], ...
            'Category', 'Linear & nonlinear visualizations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'msplot', ...
            'Description', 'A number indicating the millisecond latency at which to make the LOWESS plot ') ...
            PropertyGridField('nboot_lowess', 1000, ...
            'Category', 'Linear & nonlinear visualizations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'nboot', ...
            'Description', 'The number of bootstrapped LOWESS traces') ...
            PropertyGridField('span', .5, ...
            'Category', 'Linear & nonlinear visualizations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'span', ...
            'Description', sprintf([ 'A number in range 0 to 1. The size of the neighbourhood of points which are allowed to influence the smoothed data in each window.\n' ...
            'Increasing span increases the smoothness of the smoother. Decreasing span makes the smoother more jagged. Cleveland (1979) recommends to use a span that is as high\n' ...
            'as possible (smooth) without distorting the pattern in the data. Start with .5 and adjust as needed.'])) ...
            PropertyGridField('nbins', 1000, ...
            'Category', 'Linear & nonlinear visualizations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'nbins', ...
            'Description', 'The number of vertical bins in which to calculate kernel density. A large number of bins can substantially increase the time to plot the figure') ...
            PropertyGridField('logical_lowess', false, ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'Run LowessCI.m', ...
            'Description', 'Check box to run LowessCI.m once OK is pressed.') ...
            ];
        
        
    case 1
        
        
        
        properties = [ ...
            PropertyGridField('condnames', statslab_propgrid.condnames, ... % extract
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Extract Data', ...
            'DisplayName', 'condnames', ...
            'Description', ['labels for each condition ', ...
            'e.g. face house object']) ...
            PropertyGridField('condfiles_extract', statslab_propgrid.condfiles_extract, ...
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Extract Data', ...
            'DisplayName', 'condfiles', ...
            'Description', ['A .mat file which holds the filenames for each subject X condition. ',...
            'Leave empty and a browser will appear so that you can choose the files ']) ...
            PropertyGridField('levels', statslab_propgrid.levels, ...
            'Category', 'Extract Data', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'levels', ...
            'Description', 'levels in your design (e.g., for a 3X2 input 3 2. For a t-test (paired or unpaired) input 2).') ...
            PropertyGridField('design', statslab_propgrid.design, ...
            'Type', PropertyType('char', 'row', {'w','ww','b','bb', 'bw'}), ...
            'Category', 'Extract Data', ...
            'DisplayName', 'design', ...
            'Description', sprintf(['A keystring indicating your type of design, for example:\n', ...
            '1-way within subjects = w\n2-way within-subjects = ww\n', ...
            '1-way between-subjects = b\n2-way between-subjects = bb\nMixed designs = bw'])) ...
            PropertyGridField('savestring', statslab_propgrid.savestring, ...
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Extract Data', ...
            'DisplayName', 'savestring', ...
            'Description', sprintf(['A string that identifies your analysis ', ...
            '(e.g. occipital_GFA_analysis). The main STATS structure, which accumulates parameters, will have this string appended to it.\n', ...
            'Leave empty and a browser will appear asking for you to load a previously saved STATS structure.'])) ...
            PropertyGridField('varargin_extract', statslab_propgrid.varargin_extract, ...
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Extract Data', ...
            'DisplayName', 'varargin', ...
            'Description', sprintf(['Method to use (DV), choose one of the following:\n', ...
            '''scalpgfa'' extract the full data array for later GFA calculations\n', ...
            '''scalpchan'', {''FCz'', ''Cz''}, extract the specified channel data (if more than one chan is specified, data is averaged)\n', ...
            '''icagfa'', ''IC_file.txt'', extract data for the ICs specified in the textfile. See documentation for text file construction\n', ...
            '''icamax'',  ''IC_file.txt'', backproject ICs specified in text file to channel with maximum weight according to the ICA weight matrix'])) ...
            PropertyGridField('logical_extract', false, ...
            'Category', 'Extract Data', ...
            'DisplayName', 'Run ExtractData.m', ...
            'Description', 'Check box to run current STATSLAB module once OK is pressed.') ...
            PropertyGridField('condfiles_resample', statslab_propgrid.condfiles_resample, ... % resample
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Resample Data', ...
            'DisplayName', 'condfiles', ...
            'Description', ['A .mat file which holds the filenames for each file you would like to resample. ',...
            'Leave empty and a browser will appear so that you can choose the files ']) ...
            PropertyGridField('nboot', statslab_propgrid.nboot, ...
            'Category', 'Resample Data', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'nboot', ...
            'Description', 'number of bootstrap resamples from the single trials (default=1000)') ...
            PropertyGridField('varargin_resample', statslab_propgrid.varargin_resample, ...
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Resample Data', ...
            'DisplayName', 'varargin', ...
            'Description', sprintf(['Optional trial cap can be specified which caps the number of trials used in the resampling procedure\n', ...
            'Leave empty or set ''trialcap'', ''none'' for no trial cap\n', ...
            'Set ''trialcap'', 75 to limit resampling to 75 trials.'])) ...
            PropertyGridField('logical_resample', false, ...
            'Category', 'Resample Data', ...
            'DisplayName', 'Run ResampleData.m', ...
            'Description', 'Check box to run current STATSLAB module once OK is pressed. Will run after completion of subsequent module.') ...
            PropertyGridField('condfiles_group', statslab_propgrid.condfiles_group, ... % group stat
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Group Statistics', ...
            'DisplayName', 'condfiles', ...
            'Description', ['A .mat file which holds the filenames with "bootstrapped" appended to them (i.e., the output files of the resampling procedure), in the form of subject X condition cell arrays. ', ...
            'Leave empty and a browser will appear so that you can choose the bootstrapped files ']) ...
            PropertyGridField('alpha_group', statslab_propgrid.alpha_group, ...
            'Category', 'Group Statistics', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'alpha', ...
            'Description', 'arbitrary significance cutoff. Will be adjusted if control for FWE is selected') ...
            PropertyGridField('nsamp', statslab_propgrid.nsamp, ...
            'Category', 'Group Statistics', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'nsamp', ...
            'Description', 'Number of resamples taken at the group level (resampling of subjects). This can take a long time (default = 1000)') ...
            PropertyGridField('varargin_group', statslab_propgrid.varargin_group, ...
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Group Statistics', ...
            'DisplayName', 'varargin', ...
            'Description', sprintf(['Optional control for FWE and specification of linear contrasts.\n', ...
            'For example, consider testing all pairwise comparisons and the interaction in a 2x2 design with Rom''s method of FWE control:\n', ...
            '''FWE'', ''Rom'', ''conA'', [1 0 -1 0; 0 1 0 -1]'', ''conB'', [1 -1 0 0; 0 0 1 -1]'', ''conAB'', [1 -1 -1 1]''\n', ...
            'Do not forget the transpose operator at the end of the contrasts matrices (i.e., '' ).\n', ...
            'See documentation and function header (help GroupStatistics) for many more examples. '])) ...
            PropertyGridField('logical_group', false, ...
            'Category', 'Group Statistics', ...
            'DisplayName', 'Run GroupStatistics.m', ...
            'Description', 'Check box to run current STATSLAB module once OK is pressed. Will run after completion of subsequent module.') ...
            PropertyGridField('condfiles_subject', statslab_propgrid.condfiles_subject, ... % sub stat
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Subject Statistics', ...
            'DisplayName', 'condfiles', ...
            'Description', ['A .mat file which holds the filenames with "bootstrapped" appended to them (i.e., the output files of the resampling procedure), in the form of subject X condition cell arrays. ', ...
            'Leave empty and a browser will appear so that you can choose the bootstrapped files ']) ...
            PropertyGridField('alpha_subject', statslab_propgrid.alpha_subject, ...
            'Category', 'Subject Statistics', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'alpha', ...
            'Description', 'arbitrary significance cutoff. Will be adjusted if control for FWE is selected') ...
            PropertyGridField('varargin_subject', statslab_propgrid.varargin_subject, ...
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Subject Statistics', ...
            'DisplayName', 'varargin', ...
            'Description', sprintf(['Optional control for FWE and specification of linear contrasts.\n', ...
            'Contrast matrices are constructed in the same way as in the Group Statistics module.\n' , ...
            'However, see documentation for the exception when dealing with single-subject statistics in between-within (mixed) designs.\n'])) ...
            PropertyGridField('logical_subject', false, ...
            'Category', 'Subject Statistics', ...
            'DisplayName', 'Run SubjectStatistics.m', ...
            'Description', 'Check box to run current STATSLAB module once OK is pressed. Will run after completion of subsequent module.') ...
            PropertyGridField('infodisplay_group', true, ... % group fig
            'Category', 'Group Figure', ...
            'DisplayName', 'infodisplay', ...
            'Description', 'Numerical flag. If set STATSLAB will display condition labels and contrast matrices for reference.') ...
            PropertyGridField('varargin_groupfig', statslab_propgrid.varargin_groupfig, ...
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Group Figure', ...
            'DisplayName', 'varargin', ...
            'Description', sprintf(['Optional inputs for displaying group figures.\n', ...
            '''all'' will show figures for all previously specified contrasts. If you would like to plot only a subset of the comparisons,\n', ...
            'specify the appropriate key/val pairs. For example, to plot the 1st and 2nd factor B comparisons, as well as the 1st interaction,\n', ...
            'use ''FactorB'', [1 2], ''FactorAB'', 1\n', ...
            'See documentation and function header (help GroupFigure) for many more examples. '])) ...
            PropertyGridField('logical_groupfig', false, ...
            'Category', 'Group Figure', ...
            'DisplayName', 'Run GroupFigure.m', ...
            'Description', 'Check box to run current STATSLAB module once OK is pressed. Will run after completion of subsequent module.') ...
            PropertyGridField('infodisplay_sub', true, ... % sub fig
            'Category', 'Subject Figure', ...
            'DisplayName', 'infodisplay', ...
            'Description', 'Numerical flag. If set STATSLAB will display condition labels and contrast matrices for reference.') ...
            PropertyGridField('varargin_subjectfig', statslab_propgrid.varargin_subjectfig, ...
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Subject Figure', ...
            'DisplayName', 'varargin', ...
            'Description', sprintf(['Optional inputs for displaying subject figures. There are various visualizations available.\n', ...
            'To plot subject difference waves with specific colors and Y axis range:\n', ...
            '''plottype'', ''wave'', ''diffcol'', [.8 0 0], ''CIcol'', [0 .9 0], ''yaxis'', [-4 4]\n', ...
            'To plot subject difference waves as colorbars with a color range (caxis):\n', ...
            '''plottype'', ''diff'', ''caxis'', [-4 4]\n', ...
            'To plot subject difference waves as colorbars with margin of error information on the Y axis (i.e., mean varies by +/- some amount):\n', ...
            '''plottype'', ''MOE'', ''caxis'', [-4 4], ''zaxis'', [0 3]\n'])) ...
            PropertyGridField('logical_subjectfig', false, ...
            'Category', 'Subject Figure', ...
            'DisplayName', 'Run SubjectFigure.m', ...
            'Description', 'Check box to run current STATSLAB module once OK is pressed. Will run after completion of subsequent module.') ...
            PropertyGridField('infodisplay_cor', true, ... % winbootcor
            'Category', 'Robust Correlations', ...
            'DisplayName', 'infodisplay', ...
            'Description', 'Numerical flag. If set STATSLAB will display your contrasts, condition names, Xlables, and Ylables.') ...
            PropertyGridField('nboot_cor', statslab_propgrid.nboot_cor, ...
            'Category', 'Robust Correlations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'nboot', ...
            'Description', 'number of bootstrap resamples from the x and y data. Default=1000') ...
            PropertyGridField('tr', statslab_propgrid.tr, ...
            'Category', 'Robust Correlations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'trim', ...
            'Description', 'percentage to winsorize from the X and Y data. Keep as decimal place (e.g., .2 for 20%, .5 for 50% etc). Wilcox (2012) recommends .2 in many cases') ...
            PropertyGridField('Ylabel_cor', statslab_propgrid.Ylabel_cor, ...
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Robust Correlations', ...
            'DisplayName', 'Ylabel', ...
            'Description', sprintf(['A string, or cell array of strings, indicating your Y variable(s) that will each be correlated, one by one, with your EEG waveforms (X variable). For example,\n ', ...
            'RTs accuracy perfectionism_scores'])) ...
            PropertyGridField('varargin_cor', statslab_propgrid.varargin_cor, ...
            'Type', PropertyType('cellstr', 'row'), ...
            'Category', 'Robust Correlations', ...
            'DisplayName', 'varargin', ...
            'Description', sprintf(['String and numerical pair indicating the EEG data you would like to use in the correlation. For example, ''Condition'', 3\n' ...
            'would correlate data from condition 3 with each Y variable. To use difference waves as the X variable there are three varargin inputs. For example, ''FactorB'', 2, ''my_comparison''\n', ...
            'would use the 2nd FactorB waveform as the X variable in the correlation and name this comparison, ''my_comparison''\n', ...
            'See documentation for subtle differences when using mixed designs'])) ...
            PropertyGridField('logical_cor', false, ...
            'Category', 'Robust Correlations', ...
            'DisplayName', 'Run WinBootCor.m', ...
            'Description', 'Check box to run current STATSLAB module once OK is pressed.') ...
            PropertyGridField('condition_label_rw', statslab_propgrid.condition_label_rw, ... % Linear & nonlinear visualizations wincorboot figure
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'condition/contrast label (X variable)', ...
            'Description', 'Label of one of your conditions or contrasts that was used previously when calculating correlations.') ...
            PropertyGridField('Ylabel_rw', statslab_propgrid.Ylabel_rw, ...
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'Ylabel (Y variable)', ...
            'Description', 'Ylabel used in a previous correlation.') ...
            PropertyGridField('logical_rw', false, ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'Run WinBootCorFigure.m', ... % does not exist yet
            'Description', 'Check box to run WinBootCorFigure.m once OK is pressed.') ...
            PropertyGridField('infodisplay_slope', true, ... % slope
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'infodisplay', ...
            'Description', 'Numerical flag. If set STATSLAB will display your contrasts, condition names, Xlables, and Ylables.') ...
            PropertyGridField('condition_label_slope', statslab_propgrid.condition_label_slope, ...
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'condition/contrast label (X variable)', ...
            'Description', 'Label of one of your conditions or contrasts that was used previously when calculating correlations.') ...
            PropertyGridField('Ylabel_slope', statslab_propgrid.Ylabel_slope, ...
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'Ylabel (Y variable)', ...
            'Description', 'Ylabel used in a previous correlation.') ...
            PropertyGridField('msplot_slope', statslab_propgrid.msplot_slope, ...
            'Category', 'Linear & nonlinear visualizations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'msplot', ...
            'Description', 'A number indicating the millisecond latency at which to make the scatterplot ') ...
            PropertyGridField('CI_color_slope', [.5 .5 .5], ...
            'Category', 'Linear & nonlinear visualizations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'CI_color', ...
            'Description', 'The color of the CI and prediction band. This is in the form of an RGB triplet') ...
            PropertyGridField('CI_limit_slope', [1 1 1], ...
            'Category', 'Linear & nonlinear visualizations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'CI_limit', ...
            'Description', ' The color that the CI will fade to as it increases in width.') ...
            PropertyGridField('logical_slope', false, ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'Run SlopeCI.m', ...
            'Description', 'Check box to run SlopeCI.m once OK is pressed.') ...
            PropertyGridField('infodisplay_lowess', true, ... % LOWESS
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'infodisplay', ...
            'Description', 'Numerical flag. If set STATSLAB will display your contrasts, condition names, Xlables, and Ylables.') ...
            PropertyGridField('condition_label_lowess', statslab_propgrid.condition_label_lowess, ...
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'condition/contrast label (X variable)', ...
            'Description', 'Label of one of your conditions or contrasts that was used previously when calculating correlations.') ...
            PropertyGridField('Ylabel_lowess', statslab_propgrid.Ylabel_lowess, ...
            'Type', PropertyType('char', 'row'), ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'Ylabel (Y variable)', ...
            'Description', 'Ylabel used in a previous correlation.') ...
            PropertyGridField('msplot_lowess', statslab_propgrid.msplot_lowess, ...
            'Category', 'Linear & nonlinear visualizations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'msplot', ...
            'Description', 'A number indicating the millisecond latency at which to make the LOWESS plot ') ...
            PropertyGridField('nboot_lowess', statslab_propgrid.nboot_lowess, ...
            'Category', 'Linear & nonlinear visualizations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'nboot', ...
            'Description', 'The number of bootstrapped LOWESS traces') ...
            PropertyGridField('span', statslab_propgrid.span, ...
            'Category', 'Linear & nonlinear visualizations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'span', ...
            'Description', sprintf([ 'A number in range 0 to 1. The size of the neighbourhood of points which are allowed to influence the smoothed data in each window.\n' ...
            'Increasing span increases the smoothness of the smoother. Decreasing span makes the smoother more jagged. Cleveland (1979) recommends to use a span that is as high\n' ...
            'as possible (smooth) without distorting the pattern in the data. Start with .5 and adjust as needed.'])) ...
            PropertyGridField('nbins', statslab_propgrid.nbins, ...
            'Category', 'Linear & nonlinear visualizations', ...
            'Type', PropertyType('denserealdouble', 'matrix'), ...
            'DisplayName', 'nbins', ...
            'Description', 'The number of vertical bins in which to calculate kernel density. A large number of bins can substantially increase the time to plot the figure') ...
            PropertyGridField('logical_lowess', false, ...
            'Category', 'Linear & nonlinear visualizations', ...
            'DisplayName', 'Run LowessCI.m', ...
            'Description', 'Check box to run LowessCI.m once OK is pressed.') ...
            ];
        
end

































